apiVersion: v1
kind: Pod 
metadata:
  name: my-security-pod 
spec: 
  securityContext: 
    runAsUser: 2000
    fsGroup: 3000
  containers: 
  - name: myapp-container
    image: busybox
    command: ['sh', '-c', "cat /message/message.txt && sleep 3600"]