apiVersion: v1
kind: Pod 
metadata: 
  name: my-pod 
  labels:
    app: myapp
  namespace: my-ns
spec: 
  containers: 
  - name: myapp-container
    image: busybox 
    command: ['sh', '-c', 'Hello Kubernetes! && sleep 3600']