apiVersion: v1
kind: Pod 
metadata: 
  name: my-service-account-pod 
spec: 
  serviceAccountName: my-serviceaccount 
  containers: 
  - name: myapp-container
    image: busybox 
    command: ['sh', '-c', "echo Hello Kubernetes! && sleep 3600"]