apiVersion: v1
kind: Pod
metadata:
  name: candy-service
spec:
  securityContext:
    fsGroup: 2000
  containers:
  - name: candy-service
    image: linuxacademycontent/candy-service:1
    volumeMounts:
    - name: candy-service-config-volume
      mountPath: /etc/candy-service/
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
    env:
    - name: DB_PASSWORD
      valueFrom:
        secretKeyRef:
          name: candy-service-secret
          key: db-password
  volumes:
  - name: candy-service-config-volume
    configMap:
      name: candy-service-config